title: Sudarshan Vankudre
description: Personal website of Sudarshan Vankudre
url: https://sdrshnv.github.io
baseurl: ""

markdown: kramdown

collections:
  reviews:
    output: true
    permalink: /clothing/:name/

defaults:
  - scope:
      path: ""
      type: reviews
    values:
      layout: default

exclude:
  - README.md
